export const convertData = (obj) => {
  const {
    ambients,
    antiquity,
    apartments_per_floor,
    bath,
    between_streets,
    building_side,
    cochera,
    covered_surface,
    expenses,
    elevators,
    floor,
    floors,
    free_backyard,
    heating,
    img1,
    img2,
    img3,
    img4,
    img5,
    img6,
    img7,
    m2,
    orientation,
    price,
    professional,
    title,
    tipo_de_cochera,
    street,
    rooms,
  } = obj;

  const newTitle = title[0].text;
  return {
    title: newTitle,
    m2,
    m2Covered: covered_surface,
    orientation,
    between_streets,
    building_side,
    cochera,
    price,
    professional,
    details: {
      ambients,
      antiquity,
      apartmentsPerFloor: apartments_per_floor,
      expenses,
      elevators,
      floor,
      floors,
      free_backyard,
      heating,
      garageType: tipo_de_cochera
    },
    photos: [img1, img2, img3, img4, img5, img6, img7],
    baths: bath,
    street,
    rooms,
  }
};
